// Main exports
export type { ChatServiceApi } from "./api";
export {
  ChatMessageProcessingError,
  ChatValidationError,
  ChatConnectionError,
  ChatAgentError,
  ChatHistoryError,
  ChatStreamError,
  ChatBatchError,
  ChatOperationError,
  ChatContentError,
  ChatServiceConfigurationError,
  ChatServiceStateError,
  ChatServiceTimeoutError,
  ChatServiceResourceError,
  ChatServiceNetworkError,
} from "./errors";
export type { ChatServiceError } from "./errors";
export { ChatService } from "./service";
export type {
  ChatMessage,
  ChatAttachment,
  ChatMessageRequest,
  ChatMessageResponse,
  ChatValidationResult,
  ChatProcessingOptions,
  ChatStreamOptions,
  ChatHistoryRequest,
  ChatHistoryFilter,
  ChatHistoryResponse,
  ChatConnectionConfig,
  ChatAuthConfig,
  ChatConnectionResult,
  ChatAgentConfig,
  ChatAgentSwitchResult,
  ChatBatchRequest,
  ChatBatchResponse,
  ChatOperation,
  ChatOperationResult,
  ChatMetrics,
  ChatEventPayload,
  ChatServiceConfig,
  ChatRetryPolicy,
  ChatRateLimits,
} from "./types";
export {
  CHAT_SERVICE_CONSTANTS,
  isValidChatMessage,
  isValidChatId,
  isValidMessageContent,
  isValidAttachment,
  generateChatId,
  generateMessageId,
  generateOperationId,
  calculateMessageTokens,
  sanitizeContent,
  formatTimestamp,
  createChatMessage,
  createChatEvent,
} from "./types";
